### Ths is an example file on how to configure logging from vcenter for the agent.

### a pipeline consists of stanza blocks that sequentially or specifically flow into other outputs.
pipeline:
  # This example takes the log plugin gcve.yaml which is an abstraction of a more verbose pipeline specifically
  # to collect and send logs for GCVE

  - id: vmware-esxi-logs
    # A syslog address of the form `<ip>:<port>`
    listen_address: 0.0.0.0:514
    # Enable TLS for the TCP listener
    enable_tls: false
    # File path for the X509 TLS certificate chain, only relevant if enable_tls is true
    certificate_file: /opt/cert
    # File path for the X509 TLS private key, only relevant if enable_tls is true
    private_key_file: /opt/key
    # whether or not to start parsing logs from `end` of file (like a tail of a file) or to the `beginning` of the file
    start_at: end
    type: vmware_esxi_dfw
    output: my_project_destination

  - id: vmware-vcenter-logs
    # A syslog address of the form `<ip>:<port>`
    listen_address: 0.0.0.0:5142
    # Enable TLS for the TCP listener
    enable_tls: false
    # File path for the X509 TLS certificate chain, only relevant if enable_tls is true
    certificate_file: /opt/cert
    # File path for the X509 TLS private key, only relevant if enable_tls is true
    private_key_file: /opt/key
    # whether or not to start parsing logs from `end` of file (like a tail of a file) or to the `beginning` of the file
    start_at: end
    type: vmware_vcenter_gcve
    output: my_project_destination

  - id: vmware-nsx-logs
    listen_port: 5140
    connection_type: tcp
    type: syslog_nsx
    output: my_project_destination

  - id: my_project_destination
    project_id: PROJECT_ID
    type: google_cloud_output
